### ISSUE TITLE
Expect to disclose detailed data

### ISSUE THREAD

**Issue by zhejunliux** [Quehry/HelloBench#2]
### content 
When aligning the rankings, it was found that the benchmark model (gpt4o) generally received very low scores, making it difficult to align with the rankings.
### how to close
1. Disclose detailed scoring data
2. Disclose the detailed parameters of the requested model

**Comment by Quehry** [comment]
Hello, @zhejunliux 
Thank you for your attention to Hellobench. Due to the significant cost when using GPT-4.0 for evaluations, we don't have the budget to replicate the results of the paper again. The instability of the results could be due to:

1. Inconsistent model versioning of GPT-4o (the model version used for evaluation might differ from the current version of GPT-4o)
2. Even when controlling the generation seed, differences in results may still occur.

However, I will release the following to verify our results:

1. The generation results of all models.
2. The evaluation results and scores of GPT-4o.

To ensure that Hellobench is entirely reproducible and cost-effective, we will use open-source models (this way the model versions will not change, and the evaluations will be stable) for checklist-wise evaluations. We will release a leaderboard evaluated with open-source models on Huggingface soon.

We will have a major update to the repo soon, so please stay tuned.

**Comment by Quehry** [comment]
Additionally, i have found that the implementation of opencompass version of HelloBench exists bugs, I will fix it and soon pr to opencompass main branch

**Comment by Quehry** [comment]
I have updated the repo and release all my results.

**Comment by zhejunliux** [comment]
great job

**Comment by zhejunliux** [comment]
hello @Quehry .What is the specific release date?

**Comment by Quehry** [comment]
Hello @zhejunliux, the release date is 2024.11.19 and here is the link to the commit https://github.com/Quehry/HelloBench/commit/92c7d469230b5b6b6ee1bfc1ea2ce49cb9125b57

**Comment by zhejunliux** [comment]
Sorry for the confusion, it is about the publication date of the question 

> We will release a leaderboard evaluated with open-source models on Huggingface soon.

**Comment by Quehry** [comment]
Perhaps by the end of December or later, I apologize for not being able to provide a more specific timeframe. I have noticed that using a 72B model as a judge is very slow (even with 8 GPUs). However, we are still working hard on the evaluation and may release some of the results by the end of this month.

**Comment by zhejunliux** [comment]
Why is it slow? What is the GPU model? By the way, will you release the details of the scoring model for training? We are working on something similar here. It involves multi-constraint instruction following and evaluating based on constraint points, which seems quite similar to this kind of checklist. I hope to discuss this with you.
